name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charset_converter: ^2.0.0
  esc_pos_utils_plus: ^2.0.4
  flutter:
    sdk: flutter
  image: ^4.5.3
  intl: 0.20.2
  network_info_plus: ^6.1.0
  path_provider: ^2.1.3
  ping_discover_network_plus: ^0.0.5
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
