name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  charset_converter: ^2.0.0
  esc_pos_utils:
    path: ../esc_pos_utils
  flutter:
    sdk: flutter
  image: ^4.3.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  ping_discover_network_plus: ^0.0.5
  qr_flutter: ^4.1.0
  wifi_iot: ^0.3.19+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
